# TODO: StorybookのバグがFIXされるまで待つ https://github.com/storybookjs/storybook/issues/22591
#name: Chromatic UI Change
#on: push
#
#jobs:
#  chromatic-deployment:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Install dependencies
#        run: yarn
#      - name: Publish to Chromatic
#        uses: chromaui/action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
